name: flutter_map_open_street
description: A map usign flutter map widget and open street tiles

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.10.6"

dependencies:
  flutter:
    sdk: flutter

  flutter_map: ^5.0.0
#  location: ^4.2.0
  rxdart: ^0.27.4
#  geolocator: ^9.0.2
  flutter_map_location_marker: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
#  fonts:
#    - family: MyIcons
#      fonts:
#        - asset: assets/fonts/Icons.ttf

  module:
    androidX: true
    androidPackage: net.systemgroup.flutter_map_open_street.flutter_map_open_street
    iosBundleIdentifier: net.systemgroup.fluttermapopenstreet.flutterMapOpenStreet
