/// Flutter icons Farsan
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///     family:  Farsan
///      fonts:
///        asset: fonts/Farsan.ttf
///
///
///
import 'package:flutter/widgets.dart';

/// farsan colleague icons ///
class FIcons {
  FIcons._();

  static const _kFontFam = 'Farsan-Icons';
  static const String? _kFontPkg = null;

  static const IconData polygon =
      IconData(0xe911, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
